[browser]
title = "Sigvue Examples"
subtitle = "Explore scientific and analytical results"

[[workspaces]]
use = "digital-comms"
path = "."
id = "digital-comms"
name = "Digital Communications"
[workspaces.config]
data_root = "./data/comms"

[[workspaces]]
use = "acoustic-events-segmented"
path = "."
id = "acoustic-events-segmented"
name = "Acoustic Event Review"
[workspaces.config]
data_root = "./data/acoustic-events-segmented"

[[workspaces]]
use = "radio-astronomy-rfi"
path = "."
id = "radio-astronomy-rfi"
name = "Radio Astronomy RFI Survey"
[workspaces.config]
data_root = "./data/radio-astronomy"

[[workspaces]]
use = "lte-recording"
path = "."
id = "lte-recordings"
name = "LTE Recordings"
[workspaces.config]
data_root = "./data/lte"
filename = "*.sigmf-meta"

[[workspaces]]
use = "lfm-live"
path = "."
id = "lfm-live"
name = "LFM Live View"
[workspaces.config]
data_root = "./data/lfm-live"
